- hosts:  all
  vars:
    download_src_url: https://shibboleth.net/downloads/identity-provider/3.2.1/shibboleth-identity-provider-3.2.1.tar.gz
    download_dest_dir: /tmp/shib_install
    install_path: /opt/shibboleth-idp
  environment:
    JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-2.b15.el7_2.x86_64/jre
  tasks:
    - name: Create download directory
      file:
        path: "{{ download_dest_dir }}"
        state: directory

    - name: Download and unpack tarball
      unarchive:
        src: "{{ download_src_url }}"
        dest: "{{ download_dest_dir }}"
        copy: no
        # Have to use 'splitext | first' twice due to .tar.gz extension
        creates: "{{ download_dest_dir }}/{{ download_src_url | basename | splitext | first | splitext | first }}"

    - name: Check if Shibboleth is already installed
      stat:
        path: "{{ install_path }}"
      register: shib_installed

    - name: Install Shibboleth
      become: yes
      expect:
        timeout: 10
        command: /tmp/shibboleth/shibboleth-identity-provider-3.2.1/bin/install.sh
        responses:
          Source \(Distribution\) Directory(.*): '/tmp/shibboleth/shibboleth-identity-provider-3.2.1'
          Installation Directory(.*) : '/opt/shibboleth-idp'
          Hostname(.*) : 'syswiki02.cuny.edu'
          SAML EntityID(.*) : 'syswiki02.cuny.edu/idp/shibboleth'
          Attribute Scope(.*) : 'devlogin.cuny.edu'
          Backchannel PKCS12 Password(.*) : 'testing'
          Re-enter password(.*) : 'testing'
          Cookie Encryption Key Password(.*) : 'testing'
          Re-enter password(.*) : 'testing'
      when: shib_installed != True

    - name: Add idp.xml to tomcat
      become: yes
      blockinfile:
        dest: /etc/tomcat/Catalina/localhost/idp.xml
        create: yes
        block: |
          <Context docBase="/opt/shibboleth-idp/war/idp.war"
          privileged="true"
          antiResourceLocking="false"
          swallowOutput="true" />
