- hosts:  all
  vars:
    download_src_url: https://shibboleth.net/downloads/identity-provider/3.2.1/shibboleth-identity-provider-3.2.1.tar.gz
    download_dest_dir: /tmp/shib_install
    install_path: /opt/shibboleth-idp
    tmp_unpacked_path: "{{ download_dest_dir }}/{{ download_src_url | basename | splitext | first | splitext | first }}"
    hostname: idp.example.com
    scope_domain: example.com
    cookie_password: changeme
    keystore_password: changeme
    entity_id: https://{{ hostname }}/idp/shibboleth
  tasks:

    - name: Check if Shibboleth is already installed
      stat:
        path: "{{ install_path }}"
      register: shib_installed

    - name: Create download directory
      file:
        path: "{{ download_dest_dir }}"
        state: directory

    - name: Download and unpack tarball
      unarchive:
        src: "{{ download_src_url }}"
        dest: "{{ download_dest_dir }}"
        copy: no
        # Have to use 'splitext | first' twice due to .tar.gz extension
        creates: "{{ tmp_unpacked_path }}"

    # Fix for entity ID issue: https://issues.shibboleth.net/jira/browse/IDP-859
    - name: Create propeties file
      blockinfile:
        dest: "{{ tmp_unpacked_path }}/install.propeties"
        create: yes
        block: |
          idp.entityID= {{ entity_id }}

    - name: Install Shibboleth
      become: yes
      # View parameters in unpacked archive: bin/build.xml
      command: >
        bin/install.sh
        -Didp.src.dir="{{ tmp_unpacked_path }}"
        -Didp.target.dir="{{ install_path }}"
        -Didp.host.name="{{ hostname }}"
        -Didp.scope="{{ scope_domain }}"
        -Didp.keystore.password="{{ keystore_password }}"
        -Didp.sealer.password="{{ cookie_password }}"
        -Didp.merge.properties=install.properties
      #"
      args:
        chdir: "{{ tmp_unpacked_path }}"
        creates: "{{ install_path }}"
      environment:
        JAVA_HOME: /etc/alternatives/jre
 
    - name: Add idp.xml to tomcat
      become: yes
      blockinfile:
        dest: /etc/tomcat/Catalina/localhost/idp.xml
        create: yes
        block: |
          <Context docBase="/opt/shibboleth-idp/war/idp.war"
          privileged="true"
          antiResourceLocking="false"
          swallowOutput="true" />
